# Generated by Django 4.2.2 on 2023-06-14 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.TextField(default='SOME_STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_de_publicacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
