# Generated by Django 4.2.2 on 2023-06-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_contenido_post_fecha_de_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cuenta_del_juego',
            field=models.CharField(default='Ingrese su usuario del juego', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(default='Detalles sobre su peticion', max_length=200),
        ),
    ]
