# Generated by Django 4.2.2 on 2023-06-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_cuenta_del_juego_alter_post_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_de_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
